name: Execute

on:
  schedule:
    - cron: '0 13 * * 3'  # Every wednesday
    - cron: '0 13 * 4 *'  # Everyday in April

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run
      run: ./task-bot.py sourcebots/tasks
